### PR TITLE
CSSModules format

### PR DESCRIPTION
**Pull request by nickbalestra**
As discussed on #110 the following PR to add support for css module format: `cssmodules.css`.

- [x] Added format support
- [x] Added test/snaphot for the new format
- [x] Updated the documentation

### CODE REVIEW

**Comment by nickbalestra** [comment]
@aputinski I've signed the CLA but it still seems to shown as ❌  - Let me know if I need to do anything on my side both for the CLA and for the PR itself.

**Comment by aputinski** [comment]
Would you mind signing the CLA again? If that doesn't work, I'll reach out internally and see what's going on.

**Comment by nickbalestra** [comment]
NP, tried to sign it again, and it said again `Thanks for signing the Salesforce CLA!`. 
Still no sign of it unblocking here. Just let me know when know more or if I'll need to do anything more. Thanks!

**Comment by aputinski** [comment]
Sorry about that! I'll ping some people and see what's going on.

**Pull request merged**
