### PR TITLE
Add setup parameter

### PR DESCRIPTION
**Pull request by tomger**
A setup module has access to Theo before it executes.
Related to https://github.com/salesforce-ux/theo/issues/123

Notes:
- Errors like "not a module" or "file doesn't exist" just bubble up.
- Let me know how/if I should write a test for this.
- Started using it in our package.json build process

All comments welcome!

### CODE REVIEW

**Comment by aputinski** [comment]
This looks great! Can you add an example of the `setup.js` file in `CLI.md` so that people know you have to export a function that receives theo as the first argument?

Also, did you sign the CLA? If you did, I might have to close.re-open this PR for the bot to pick it up.

**Comment by aputinski** [comment]
You should be able to add a test in https://github.com/salesforce-ux/theo/blob/master/bin/__tests__/theo.spec.js that does ` --setup bin/__fixtures__/setup.js`, uses the `--format` defined in the setup file, and then assert the output matches a snapshot.

**Comment by aputinski** [comment]
@tomger any idea if you'll have a chance to add the test so we can get this merged?

**Comment by tomger** [comment]
@aputinski I totally lost track of this. The notification got buried in tons of commit emails.

- added a test to the spec file
- added --setup information in CLI.md
- signed CLA

**Comment by aputinski** [comment]
This looks great! I'll publish a new npm version on Monday.

**Comment by aputinski** [comment]
`6.0.0-beta.10` is now available. Thanks again!

**Pull request merged**
