### PR TITLE
Add support for node_module imports

### LINKED ISSUE #136: Add support for node_module imports
At present the `imports` field only allows for relative file imports.
```json
"imports": ["./some/dir/file.json"]
```
I'd like to add support for node_module imports so tokens can be separately packaged and distributed.
```json
"imports": ["package-name"]
```
Would that be something you're interested in adding? If so, I'm happy to submit a PR.

### PR DESCRIPTION
**Pull request by stevenbenisek**
:sparkles: Add support for node_module imports
:books:Update docs: add import resolution
:rotating_light: Add node_module import test

Resolves #136

### CODE REVIEW

**Comment by stevenbenisek** [comment]
:boom: Possible breaking change

This was in the docs: https://github.com/salesforce-ux/theo#example 
```
imports:
  - aliases.yml
```
It won't work anymore. Now you'd have to write:
```
imports:
  - ./aliases.yml
```
I couldn't find any usage of the first example in https://github.com/salesforce-ux/design-system/tree/master/design-tokens so I'm not sure if this should be labeled as a breaking change or a bug in the current versions docs/implementation.

**Comment by aputinski** [comment]
This looks great!

As far as the breaking change, because it was in the docs we should probably make a major release.

**Comment by stevenbenisek** [comment]
That seems like the sensible thing to do 😄

**Comment by aputinski** [comment]
I'll try to get that released in the next few days.

**Pull request merged**
