### PR TITLE
CLI

### LINKED ISSUE #113: Theo-cli
Hi @aputinski ,
I'm putting together a little CLI tool around Theo and I wanted to share it here.

https://github.com/opentable/design-tokens/tree/master/tools/theo-cli

### PR DESCRIPTION
**Pull request by nickbalestra**
Hi Adam, as per #113 this PR attempt to add the CLI I did build within Theo itself.
Few things:

- I've added a link to the whole documentation in the main readme. (I've created a separated doc file  to avoid cluttering the main readme, but I'll leave this to you if you want to move things around or re-arrange).

- I've added some basic integration tests that rely on the already avail `__fixture__`

- This closes #113 

Please let me know if I can help further.

### CODE REVIEW

**Comment by aputinski** [comment]
@nickbalestra Thanks for the PR! I have a few high-level comments about the API and I think it will be easier for me to make the actual changes rather than writing out my thoughts. I'm going to merge this into a `cli` branch and then make the changes there.

**Comment by aputinski** [comment]
Ok, so I made my changes in this commit: https://github.com/salesforce-ux/theo/commit/06758f42014a5af423b287e6331b8f5c2657d377

Here's a basic rundown:
- Changed the usage to `theo <[file]> [options]`
- Removed the naming convention
- Made writing to the file system optional by passing the `--dest` flag. By default it will just print the result to `stdout`.

Thanks again for getting this started!

**Comment by nickbalestra** [comment]
Love the changes! Thanks for the help and effort

**Comment by nickbalestra** [comment]
@aputinski any ideas on when you think this branch will land in production/published? Is there anything else I can do to help out with it?

**Comment by aputinski** [comment]
I'll work on getting this into a beta tomorrow

**Comment by aputinski** [comment]
I just published `6.0.0-beta.3`. Please let me know if you encounter any bugs.

**Comment by caseycallow** [comment]
Thanks for publishing. Getting this even after fresh NPM install: `| => npm i -D theo
npm ERR! path /Users/casey/Projects/design-tokens/node_modules/theo/bin/theo.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/casey/Projects/design-tokens/node_modules/theo/bin/theo.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent `

**Comment by nickbalestra** [comment]
Could this related to the `.npmignore` file not being updated before publishing? As it seems that some files are not published to me

**Pull request merged**
