### PR TITLE
Moves value from from attribute

### LINKED ISSUE #142: Android.xml value in attribute
Documented android.xml format:
```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
  <property name="PROP_NAME" type="PROP_TYPE" category="PROP_CATEGORY">PROP_VALUE</property>
  <color name="PROP_NAME" type="color" category="PROP_CATEGORY">PROP_VALUE</color>
</resources>
```

However, the format generated has the [value as an attribute](https://github.com/salesforce-ux/theo/blob/master/lib/__tests__/__snapshots__/formats.js.snap#L4-L11).

### PR DESCRIPTION
**Pull request by craveytrain**
Simple syntax adjustment to move the value to it's proper place based on the [examples](https://github.com/dylang/node-xml).

Resolves #142

### CODE REVIEW

**Comment by aputinski** [comment]
Good catch — we'll probably have to bump to `8.0.0` though because this would break anyone relying on the broken behavior.

**Comment by craveytrain** [comment]
Makes sense to me. Happy to help.

**Comment by aputinski** [comment]
I haven't forgotten about this PR — I'll merge this in with #146 and since it will also be a major version bump.

**Comment by craveytrain** [comment]
Sounds good.

**Comment by craveytrain** [comment]
That's the format my android developers were looking for but I confess I'm not familiar with the platform requirements myself.

**Comment by larsonjj** [comment]
Hey @craveytrain and @aputinski,

Just wanted to chime in on this PR as it's a start in the right direction. After chatting with an Android engineer on my team, it seems that `<property>` tags don't really mean anything when it comes to Android resources. Apparently each value should be mapped to a tag that matches it's type.

For example, all colors should be mapped to the `<color>` tag, all dimensions (px, rem) should be mapped to the `<dimen>` tag, etc.

More info in the Android docs: https://developer.android.com/guide/topics/resources/providing-resources.html

**Pull request merged**
