### PR TITLE
Register new Theo formats associated with leveraging CSS custom properties

### PR DESCRIPTION
**Pull request by lozandier**
## PR Aims
- [x] Add a default CSS Custom Properties Formatter 
- [x] Add a Theo formatter for CSS Custom Properties for the usual common default of setting it as "default" values using `:root` that's similar to the existing `default.scss` Theo formatter
- [ ] Ensure the new formats comply with the explicit/implicit code conventions of the current file 
- [ ] Ensure tests are written that conform to the current expectations of Theo contributors
## Important things to be discussed and thought about with the review
- Is the naming of the new formatters sensical?
- Is the formatter associated with SCSS variables & the CSS custom property versions of such variables of value as I think it is? 
- Need guidance on the test conventions to write the tests or is someone already assigned to do for other contributors? 
## Estimated Review TIme

Since no tests were written yet because of questions of how it's done in this repo and an understanding of [CSS custom properties](https://www.w3.org/TR/css-variables/) and [how Sass handles CSS custom properties moving forward](https://github.com/sass/sass/issues/1128) , I expect the estimated review time being **10-15-25 minutes** 
## Recommended reviewers
- @kaelig, being involved with the changed files
- @jina, being a Sass Jedi (very knowledgeable about Sass and the most inclusive patterns towards using it well)
- Other core contributors since this adds new default formatters that may not be named at this time in a matter that may not make sense yet to the vision of Theo being the awesome thing it is at the moment.

### CODE REVIEW

**Comment by kaelig** [comment]
I like where this is going. Looking forward to seeing some tests in there.

**Comment by lozandier** [comment]
@kaelig Maybe I'm having a slow start to my day, but I', actually having a hard time understanding how to set up my tests or running the local version of Theo; is there a `md` file about it I haven't seen yet?

**Comment by aputinski** [comment]
@lozandier thanks for the PR!

Since you've submitted the PR, I'll assume you have the repo cloned locally, so just `cd` into the directory and run the following:

```bash
npm install
npm test
```

After that, you can copy a test case we already have for one of the other formats:
https://github.com/salesforce-ux/theo/blob/master/test/props/index.js#L627

```javascript
describe('custom-properties.css', function() {
  before($format('raw', 'custom-properties.css', paths.sample));
  it('creates custom-properties.css syntax', function() {
    // "result" will be a string returned by your formatter using the "mocks/sample.json" file
    // from here, you can assert that certain patterns are found
    assert(result.match(/pattern-a/));
  });
  it('some other test', function() {
    assert(result.match(/pattern-b/));
  });
});
```

**Comment by lozandier** [comment]
@aputinski Gotcha, not too far away what I thought would be the case then; thought too much about the Gulp part it seems.

I'll get started on such tests after the end of the business day for me PST.

**Comment by kaelig** [comment]
Hi @lozandier, thanks again for your help. Is this something you'd still like to work on?

**Comment by kaelig** [comment]
Closing this as Theo v6 (currently in Alpha) now features Handlebars templates which should make it easy to support CSS custom properties.

**Pull request closed without merging**
